protected/controllers/ReportController.php
<?php

class ReportController extends Controller
{
	public function actionIndex()
	{
        $this->customPageTitle = 'Звіти';

        $criteria = new CDbCriteria();
        $criteria->addInCondition('status', ['completed', 'early']);
        $criteria->order = 'end_date DESC';
        $criteria->limit = 2;

        if (!$projects = Yii::app()->cache->get('projects_completed')) {
            if ($projects = Project::model()->findAll($criteria)) {
                Yii::app()->cache->set('projects_completed', $projects);
            }
        }

        $this->render(
            'index',
            [
                'projects' => $projects,
            ]
        );
	}

	public function actionView($id=0)
	{
        $this->customPageTitle = 'Звіт';

        /** @var $project Project */
        $project = Yii::app()->cache->get('project'.$id);
        if (!$project) {
            if ($project = Project::model()->findByPk((int)$id)) {
                Yii::app()->cache->set('project'.$id, $project);
            }
        }

        if (!$id || !$project) {
            throw new CHttpException(404, 'Данная страница не найдена.');
        }

        $this->render(
            'view',
            [
                'project' => $project,
            ]
        );
	}

	// Uncomment the following methods and override them if needed
	/*
	public function filters()
	{
		// return the filter configuration for this controller, e.g.:
		return array(
			'inlineFilterName',
			array(
				'class'=>'path.to.FilterClass',
				'propertyName'=>'propertyValue',
			),
		);
	}

	public function actions()
	{
		// return external action classes, e.g.:
		return array(
			'action1'=>'path.to.ActionClass',
			'action2'=>array(
				'class'=>'path.to.AnotherActionClass',
				'propertyName'=>'propertyValue',
			),
		);
	}
	*/
}

protected/views/layouts/_completed.php
<?php
/**
 * Project: HelpingOur (crowd.dev)
 * File:    _completed.php
 * Date:    09.09.14 @ 16:18
 *
 * Author:  Victor Burak <victor.burre@gmail.com>
 */
?>
<div class="completed_projects">
    <div class="body">
        <h1>Завершені проекти</h1>

        <div class="slideshow_nav">
            <a href=# id="slide_prev">Prev</a>

            <div id="slide_caption">
                <span class="slideNum"></span>
                із
                <span class="slideCount"></span>
            </div>
            <a href=# id="slide_next">Next</a>
        </div>
        <?php
            $projects = Project::getAllByStatus(['completed', 'early']);
            $i = 0;
        ?>
        <div class="projects_slider">
        <?php foreach ($projects as $project): ?>
        <?php if ($i%4 == 0): ?>
            <div class="slide">
        <?php endif ?>
                <div class="project completed">
                    <h3><?php echo $project->title; ?></h3>
                    <?php $project->getImages(); ?>
                    <div class="photo">
                        <img src="/<?php echo $project->images[0];?>"/>
                        <img src="/images/ico/done.png" class="sticker"/>
                        <a href="<?php echo $this->createUrl('report/view', ['id'=>$project->id]) ?>" class="button">отчет</a>
                    </div>
                    <div class="description">
                        <?php echo $project->trim('description', 230); ?>
                    </div>
                    <div class="progress_wrapper">
                        <div class="progress_bar">
                            <div class="progress" style="width: <?php echo $project->getCollectedPercentage(); ?>%"></div>
                            <div class="progress_percent"><?php echo $project->getCollectedPercentage(); ?>%</div>
                        </div>
                        <div class="info">
                            <div class="collected">
                                <div class="info_title"><?php echo (int)$project->getCollectedSum(); ?></div>
                                <div>зібрано</div>
                            </div>
                            <div class="members">
                                <div class="info_title"><?php echo $project->getMemberCount(); ?></div>
                                <div>участника</div>
                            </div>
                            <div class="budget">
                                <div class="info_title"><?php echo (int)$project->target_sum; ?></div>
                                <div>грн. потрібно</div>
                            </div>
                        </div>
                    </div>
                </div>
        <?php $i++; ?>
        <?php if ($i%4 == 0 || $i == count($projects)): ?>
            </div> <!-- .slide -->
        <?php endif ?>
        <?php endforeach ?>
        </div>
    </div>
</div>

<script>
//    $(document).ready(function () {
//        var d = $('div.slide > div.completed > div.description');
//        var maxH = 0;
//
//        for (var i = 0; i < d.length; i++) {
//            h = $(d[0]).height();
//            if (h > maxH) maxH = h;
//        }
//
//        $('div.slide > div.completed > div.description').height(maxH);
//    });
</script>

protected/views/layouts/_footer.php
<?php
/**
 * Project: HelpingOur (crowd.dev)
 * File:    _footer.php
 * Date:    09.09.14 @ 16:52
 *
 * Author:  Victor Burak <victor.burre@gmail.com>
 */
?>
<div class="footer">
    <div class="body">
        <div>
            допомогаю нашим | проект допомоги україинським бійцам (c) 2014
        </div>
        <ul class="socials">
            <li>
                <a href="#" class="vk" ></a>
            </li>
            <li>
                <a href="#" class="tw" ></a>
            </li>
            <li>
                <a href="#" class="email" ></a>
            </li>
            <li>
                <a href="#" class="fb" ></a>
            </li>
            <li>
                <a href="#" class="yt" ></a>
            </li>
        </ul>
    </div>
</div>

protected/views/layouts/_header.php
<?php
/**
 * Project: HelpingOur (crowd.dev)
 * File:    _header.php
 * Date:    09.09.14 @ 16:53
 *
 * Author:  Victor Burak <victor.burre@gmail.com>
 */
?>
<div class="header">
    <div class="body">
        <div class="clear">
            <a href="/" class="logo" >
                <img src="/images/logo.png" />
            </a>
            <ul class="menu">
                <li>
                    <a href="/about">про проект</a>
                </li>
                <li>
                    <a href="/project">в роботі</a>
                </li>
                <li>
                    <a href="/report">звіти</a>
                </li>
                <li>
                    <a href="/join">приєднатися до проекту</a>
                </li>
            </ul>
            <ul class="lang">
                <li>
                    <a href="#" class="ru" ></a>
                </li>
                <li>
                    <a href="#" class="ua" ></a>
                </li>
            </ul>
            <ul class="socials">
                <li>
                    <a href="#" class="vk" ></a>
                </li>
                <li>
                    <a href="#" class="tw" ></a>
                </li>
                <li>
                    <a href="#" class="email" ></a>
                </li>
                <li>
                    <a href="#" class="fb" ></a>
                </li>
                <li>
                    <a href="#" class="yt" ></a>
                </li>
            </ul>
        </div>
    </div>
</div>

protected/views/layouts/_partners.php
<?php
/**
 * Project: HelpingOur (crowd.dev)
 * File:    _partners.php
 * Date:    09.09.14 @ 16:11
 *
 * Author:  Victor Burak <victor.burre@gmail.com>
 */
?>
<div class="body">
    <h1>Партнери</h1>
    <div class="clear tac">
        <div class="partners">
            <?php
                $criteria = new CDbCriteria();
                $criteria->limit = 6;
                $partners = Partner::model()->findAll($criteria);
            ?>
            <?php foreach ($partners as $partner): ?>
                <a href="#">
                    <img src="/<?php echo $partner->logo; ?>" />
                </a>
            <?php endforeach ?>
        </div>
    </div>
</div>

protected/views/layouts/column1.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>

    <div class="content">
        <?php echo $content; ?>

        <?php $this->renderPartial('//layouts/_completed') ?>

        <?php $this->renderPartial('//layouts/_partners') ?>
    </div>

<?php $this->endContent(); ?>

protected/views/layouts/column2.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div class="span-19">
    <div class="content">
		<?php echo $content; ?>
    </div>
</div>
<div class="span-5 last">
	<div id="sidebar">
	<?php
		$this->beginWidget('zii.widgets.CPortlet', array(
			'title'=>'Operations',
		));
		$this->widget('zii.widgets.CMenu', array(
			'items'=>$this->menu,
			'htmlOptions'=>array('class'=>'operations'),
		));
		$this->endWidget();
	?>
	</div><!-- sidebar -->
</div>
<?php $this->endContent(); ?>

protected/views/layouts/main.php
<?php /* @var $this Controller */ ?>
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title><?php echo CHtml::encode($this->pageTitle); ?></title>
</head>
<body>
<div class="mask"></div>

<?php $this->renderPartial('//layouts/_header') ?>

<?php echo $content; ?>

<?php $this->renderPartial('//layouts/_footer') ?>

</body>
</html>